### ISSUE TITLE
[Bug]: geofencing crashes

### ISSUE THREAD

**Issue by Frank-Buss** [android/platform-samples#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which area is the issue?

Location

### What happened?

When I start the "Location - Create and monitor Geofence" example, it crashes. I have a Pixel 7 Pro, with Android 15.

### Relevant logcat output

```shell
2024-12-18 12:05:17.453 32733-32733 WindowOnBackDispatcher  com.example.platform.app             W  sendCancelIfRunning: isInProgress=false callback=androidx.activity.OnBackPressedDispatcher$Api34Impl$createOnBackAnimationCallback$1@5562933
2024-12-18 12:05:17.458 32733-411   HWUI                    com.example.platform.app             D  endAllActiveAnimators on 0xb40000796b807080 (UnprojectedRipple) with handle 0xb4000079bb7b7eb0
2024-12-18 12:05:18.154 32733-32733 VRI[MainActivity]       com.example.platform.app             D  visibilityChanged oldVisibility=true newVisibility=false
2024-12-18 12:05:18.187 32733-32733 WindowOnBackDispatcher  com.example.platform.app             W  sendCancelIfRunning: isInProgress=false callback=androidx.activity.OnBackPressedDispatcher$Api34Impl$createOnBackAnimationCallback$1@88481e6
2024-12-18 12:14:09.174 32733-32733 AndroidRuntime          com.example.platform.app             E  FATAL EXCEPTION: main
                                                                                                    Process: com.example.platform.app, PID: 32733
                                                                                                    java.lang.SecurityException: com.example.platform.app: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3231)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3215)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3198)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3140)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6092)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Frank-Buss** [comment]
Any news on this? Can someone reproduce it and fix it?
