### ISSUE TITLE
[Bug]: Search box crashes

### ISSUE THREAD

**Issue by yaraki** [android/platform-samples#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which area is the issue?

General

### In a specific sample?

n/a

### What happened?

Clicking on the search icon should open the text field, but it crashes.

### Relevant logcat output

```shell
2023-06-02 10:24:53.787 22602-22602 AndroidRuntime          com.example.platform.app             E  FATAL EXCEPTION: main
   Process: com.example.platform.app, PID: 22602
   java.lang.NoSuchMethodError: No virtual method
   textFieldColors-l59Burw(JJJJJLandroidx/compose/foundation/text/selection/TextSelectionColors;JJJJJJJJJJJJJJJJJJJJJJLandroidx/compose/runtime/Composer;IIII)Landroidx/compose/material3/TextFieldColors; in
   class Landroidx/compose/material3/TextFieldDefaults; or its super classes (declaration of
   'androidx.compose.material3.TextFieldDefaults' appears in
   /data/app/~~C2Nv-i5YBXTT8cRncVCgqw==/com.example.platform.app-0fMHkMpgm4Eb5m48dJFISQ==/base.apk)
   	at
   com.google.android.catalog.framework.ui.components.SearchTopAppBarKt.SearchTopAppBar(SearchTopAppBar.kt:84)
   	at
   com.google.android.catalog.framework.ui.CatalogScreenKt$CatalogScreen$1$2.invoke(CatalogScreen.kt:148)
   	at
   com.google.android.catalog.framework.ui.CatalogScreenKt$CatalogScreen$1$2.invoke(CatalogScreen.kt:146)
   	at
   androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:135)
   	at
   androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
   	at
   androidx.compose.animation.AnimatedContentKt$AnimatedContent$7$1$4.invoke(AnimatedContent.kt:701)
   	at
   androidx.compose.animation.AnimatedContentKt$AnimatedContent$7$1$4.invoke(AnimatedContent.kt:691)
   	at
   androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
   	at
   androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
   	at
   androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl(AnimatedVisibility.kt:939)
   	at
   androidx.compose.animation.AnimatedVisibilityKt.AnimatedVisibility(AnimatedVisibility.kt:607)
   	at
   androidx.compose.animation.AnimatedContentKt$AnimatedContent$7$1.invoke(AnimatedContent.kt:681)
   	at
   androidx.compose.animation.AnimatedContentKt$AnimatedContent$7$1.invoke(AnimatedContent.kt:664)
   	at
   androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
   	at
   androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
   	at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:714)
   	at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:134)
   	at
   com.google.android.catalog.framework.ui.CatalogScreenKt$CatalogScreen$1.invoke(CatalogScreen.kt:135)
   	at
   com.google.android.catalog.framework.ui.CatalogScreenKt$CatalogScreen$1.invoke(CatalogScreen.kt:134)
   	at
   androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
   	at
   androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
   	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:162)
   	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2486)
   	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2754)
   	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3385)
   	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3363)
   	at
   androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
   	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown
   Source:1)
   	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3363)
   	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3328)
   	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:772)
   	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1047)
   	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
   	at
   androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:541)
   	at
   androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:510)
   	at
   androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
E  	at
   androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
   	at
   androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
   	at
   androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
   	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
   	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
   	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
   	at android.view.Choreographer.doFrame(Choreographer.java:827)
   	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
   	at android.os.Handler.handleCallback(Handler.java:942)
   	at android.os.Handler.dispatchMessage(Handler.java:99)
   	at android.os.Looper.loopOnce(Looper.java:201)
   	at android.os.Looper.loop(Looper.java:288)
   	at android.app.ActivityThread.main(ActivityThread.java:7898)
   	at java.lang.reflect.Method.invoke(Native Method)
   	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
   	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
   	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@7c25519, androidx.compose.ui.platform.MotionDurationScaleImpl@e0209de, StandaloneCoroutine{Cancelling}@59407bf, AndroidUiDispatcher@71dae8c]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yaraki** [comment]
I've been trying to fix this, but no clue so far. It seems that the crash is in the catalog framework, so I tested casa-android, but it works fine.
